export const offers = [
  {
    id: "lucya",
    slug: "lucya",
    name: "Lucya",
    category: "Assurance-vie",
    bonusLabel: "Prime selon conditions",
    bonusAmount: null,
    currency: "EUR",
    searchTitle: "Code Lucya CNP - septembre 2026",
    searchDescription: "Retrouvez le code de parrainage Lucya CNP et les conditions de l'offre de septembre 2026.",
    periodLabel: "Septembre 2026",
    validThrough: null,
    description: "Une offre de parrainage Lucya à consulter selon les conditions en vigueur.",
    referralUrl: "https://www.assurancevie.com/informations/ouvrir-un-contrat.html?utm_source=Parrainage_Espace-client&utm_medium=Espace-client&utm_campaign=Parrainage_Espace-client",
    code: "GACH120179",
    requiresCode: true,
    conditions: "Montant et conditions à vérifier sur la page officielle Lucya.",
    active: true,
    featured: true,
    updatedAt: "2026-09-20"
  },
  {
    id: "boursorama",
    slug: "boursorama",
    name: "Boursorama",
    category: "Banque en ligne",
    bonusLabel: "Accès par lien direct",
    bonusAmount: null,
    currency: "EUR",
    searchTitle: "Code parrainage Boursorama - septembre 2026",
    searchDescription: "Retrouvez le code de parrainage Boursorama et les conditions de l'offre de septembre 2026.",
    periodLabel: "Septembre 2026",
    validThrough: null,
    description: "Une offre de parrainage Boursorama à consulter selon les conditions en vigueur.",
    referralUrl: "https://bour.so/p/0gvHMoxzM6o",
    code: null,
    requiresCode: false,
    conditions: "Aucun code à saisir : utilisez le lien de parrainage direct.",
    active: true,
    featured: true,
    updatedAt: "2026-09-20"
  },
  {
    id: "fortuneo",
    slug: "fortuneo",
    name: "Fortuneo",
    category: "Banque en ligne",
    bonusLabel: "Prime selon conditions",
    bonusAmount: null,
    currency: "EUR",
    searchTitle: "Code parrainage Fortuneo - septembre 2026",
    searchDescription: "Retrouvez le code de parrainage Fortuneo et les conditions de l'offre de septembre 2026.",
    periodLabel: "Septembre 2026",
    validThrough: null,
    description: "Une offre de parrainage Fortuneo à consulter selon les conditions en vigueur.",
    referralUrl: "https://www.fortuneo.fr/compte-bancaire/souscrire/choix-type-compte",
    code: "13058591",
    requiresCode: true,
    conditions: "Montant et conditions à vérifier sur la page officielle Fortuneo.",
    active: true,
    featured: true,
    updatedAt: "2026-09-20"
  }
];